const e=require('express'),a=require('axios'),c=require('cheerio'),r=require('cors'),{URL:U}=require('url'),x=require('crypto'),app=e(),P=process.env.PORT||3000;
app.use(r()),app.use(e.json()),app.use(e.static('public'));
const SE=['.html','.htm','.php','.asp','.aspx','.jsp','.css','.js','.json','.png','.jpg','.jpeg','.gif','.svg','.webp','.ico','.mp4','.mp3','.avi','.mov','.wav','.ogg','.pdf','.doc','.docx','.txt','.xml','.woff','.woff2','.ttf','.eot'];
const SH=['content-security-policy','x-frame-options','x-content-type-options','strict-transport-security','referrer-policy','permissions-policy','feature-policy','x-xss-protection'];
const AS=['[class*="advert"]','[class*="adsense"]','[class*="ad-unit"]','[class*="ad_unit"]','[id*="adsense"]','[id*="advert"]','[class*="banner-ad"]','[class*="ad-banner"]','[id*="ad-banner"]','[class*="ads-container"]','[id*="ads-container"]','[class*="advertisement"]','[id*="advertisement"]','[class*="sponsored"]','[class*="dfp-ad"]','[id*="dfp"]','[class*="google-ad"]','[id*="google_ads"]','[class*="outbrain"]','[class*="taboola"]','[id*="taboola"]','[class*="mgid"]','[class*="revcontent"]','[class*="zergnet"]','[class*="criteo"]','[class*="rubicon"]','[class*="openx"]','[class*="pubmatic"]','[class*="appnexus"]','[class*="ad-slot"]','[id*="ad-slot"]','[data-ad]','[data-adunit]','.adsbox','.ad-wrapper','ins.adsbygoogle','[class*="popup-ad"]','[class*="interstitial"]','[class*="ad-overlay"]','[class*="sticky-ad"]','[class*="float-ad"]'];
const TP=[/google-analytics\.com/,/googletagmanager\.com/,/doubleclick\.net/,/facebook\.net\/en_US\/fbevents/,/twitter\.com\/i\/adsct/,/bat\.bing\.com/,/analytics\.twitter\.com/,/connect\.facebook\.net/,/pixel\.facebook\.com/,/hotjar\.com/,/clarity\.ms/,/mouseflow\.com/,/fullstory\.com/,/mixpanel\.com/,/segment\.io/,/heap\.io/,/intercom\.io/,/drift\.com/,/hubspot\.com\/hs-script/,/scorecard\.com/,/quantserve\.com/,/scorecardresearch\.com/,/comscore\.com/,/omtrdc\.net/,/2o7\.net/,/atdmt\.com/,/adnxs\.com/,/serving-sys\.com/,/advertising\.com/];
function iA(u){try{return new U(u),!0}catch{return!1}}
function mA(rel,base){try{return iA(rel)?rel:new U(rel,base).href}catch{return rel}}
function iS(u){try{const p=new U(u).pathname.toLowerCase();return SE.some(ex=>p.endsWith(ex))}catch{return!u.includes('.')||SE.some(ex=>u.toLowerCase().includes(ex))}}
function gI(u,t=''){const l=u.toLowerCase();if(t.includes('image')||['.png','.jpg','.jpeg','.gif','.webp','.svg','.ico'].some(ex=>l.includes(ex)))return'fas fa-image';if(l.includes('.css'))return'fab fa-css3-alt';if(l.includes('.js'))return'fab fa-js-square';if(l.includes('.pdf'))return'fas fa-file-pdf';if(['.mp4','.avi','.mov','.webm'].some(ex=>l.includes(ex)))return'fas fa-video';if(['.mp3','.wav','.ogg'].some(ex=>l.includes(ex)))return'fas fa-music';return'fas fa-file'}
async function gVD(url,$,html){try{const uo=new U(url);const fav=$('link[rel="icon"],link[rel="shortcut icon"],link[rel="apple-touch-icon"]').first().attr('href')||'/favicon.ico';const favA=mA(fav,url);const ogI=$('meta[property="og:image"]').attr('content')||$('meta[name="twitter:image"]').attr('content')||'';const ogIA=ogI?mA(ogI,url):'';const lS=['img[src*="logo"]','img[alt*="logo" i]','img[class*="logo" i]','img[id*="logo" i]','[class*="logo"] img','[id*="logo"] img','header img','nav img','.brand img','a.navbar-brand img'];let lo='';for(const s of lS){const el=$(s).first();if(el.length){const src=el.attr('src');if(src){lo=mA(src,url);break}}}
const cc=[];$('style').each((i,el)=>{const t=$(el).html()||'';(t.match(/#([0-9a-fA-F]{6})\b/g)||[]).slice(0,20).forEach(co=>{if(!cc.includes(co))cc.push(co)})});
const ic=[];$('[style]').each((i,el)=>{const s=$(el).attr('style')||'';(s.match(/#([0-9a-fA-F]{6})\b/g)||[]).forEach(co=>{if(!ic.includes(co))ic.push(co)})});
const aC=[...new Set([...cc,...ic])].slice(0,8);const tc=$('meta[name="theme-color"]').attr('content')||'';if(tc&&!aC.includes(tc))aC.unshift(tc);
const ss=`https://image.thum.io/get/width/1200/crop/800/${encodeURIComponent(url)}`;
const pub=$('meta[property="og:site_name"]').attr('content')||uo.hostname;const au=$('meta[name="author"]').attr('content')||$('meta[property="article:author"]').attr('content')||'';const dt=$('meta[property="article:published_time"]').attr('content')||$('time[datetime]').first().attr('datetime')||'';
return{logo:lo,favicon:favA,ogImage:ogIA,screenshot:ss,palette:aC,publisher:pub,author:au,date:dt,lang:$('html').attr('lang')||''}}catch(err){return{}}}
function dT($,html){const t=[],h=html.toLowerCase();if(h.includes('wp-content')||h.includes('wp-includes'))t.push({name:'WordPress',category:'CMS',icon:'fab fa-wordpress',confidence:'high'});if(h.includes('shopify'))t.push({name:'Shopify',category:'E-Commerce',icon:'fas fa-shopping-bag',confidence:'high'});if(h.includes('wix.com')||h.includes('wixstatic'))t.push({name:'Wix',category:'Website Builder',icon:'fas fa-globe',confidence:'high'});if(h.includes('squarespace'))t.push({name:'Squarespace',category:'Website Builder',icon:'fas fa-square',confidence:'high'});if(h.includes('drupal'))t.push({name:'Drupal',category:'CMS',icon:'fab fa-drupal',confidence:'high'});if(h.includes('gatsby'))t.push({name:'Gatsby',category:'Framework',icon:'fas fa-bolt',confidence:'medium'});if(h.includes('next/dist')||h.includes('__next'))t.push({name:'Next.js',category:'Framework',icon:'fas fa-bolt',confidence:'high'});if(h.includes('nuxt')||h.includes('__nuxt'))t.push({name:'Nuxt.js',category:'Framework',icon:'fab fa-vuejs',confidence:'high'});if(h.includes('react')&&(h.includes('reactdom')||h.includes('react-root')||$('[data-reactroot]').length))t.push({name:'React',category:'Library',icon:'fab fa-react',confidence:'high'});if(h.includes('vue.js')||$('[v-app]').length)t.push({name:'Vue.js',category:'Framework',icon:'fab fa-vuejs',confidence:'high'});if(h.includes('angular')||$('[ng-app]').length)t.push({name:'Angular',category:'Framework',icon:'fab fa-angular',confidence:'high'});if(h.includes('jquery'))t.push({name:'jQuery',category:'Library',icon:'fas fa-code',confidence:'high'});if(h.includes('bootstrap'))t.push({name:'Bootstrap',category:'CSS Framework',icon:'fab fa-bootstrap',confidence:'high'});if(h.includes('tailwind'))t.push({name:'Tailwind CSS',category:'CSS Framework',icon:'fas fa-wind',confidence:'high'});if(h.includes('google-analytics')||h.includes('gtag'))t.push({name:'Google Analytics',category:'Analytics',icon:'fab fa-google',confidence:'high'});if(h.includes('googletagmanager'))t.push({name:'Google Tag Manager',category:'Tag Manager',icon:'fab fa-google',confidence:'high'});if(h.includes('hotjar'))t.push({name:'Hotjar',category:'Analytics',icon:'fas fa-fire',confidence:'high'});if($('link[href*="fonts.googleapis.com"]').length)t.push({name:'Google Fonts',category:'Fonts',icon:'fab fa-google',confidence:'high'});if(h.includes('fontawesome'))t.push({name:'Font Awesome',category:'Icons',icon:'fas fa-icons',confidence:'high'});return t}
function dBP($,html,headers={}){const sg=[],h=html.toLowerCase(),hd=headers;
if(hd['cf-ray']||h.includes('cloudflare')||h.includes('__cf_bm'))sg.push({name:'Cloudflare',category:'WAF/CDN',severity:'info',detail:hd['cf-ray']?`CF-Ray: ${hd['cf-ray']}`:'HTML pattern',icon:'fas fa-cloud'});
if(hd['x-amzn-requestid']||hd['x-amz-cf-id'])sg.push({name:'AWS CloudFront',category:'CDN/WAF',severity:'info',detail:'Amazon headers',icon:'fab fa-aws'});
if(hd['x-sucuri-id']||h.includes('sucuri'))sg.push({name:'Sucuri WAF',category:'WAF',severity:'info',detail:'Sucuri WAF',icon:'fas fa-shield-alt'});
if(hd['x-akamai-request-id'])sg.push({name:'Akamai',category:'CDN/WAF',severity:'info',detail:'Akamai CDN',icon:'fas fa-server'});
if(hd['x-fastly-request-id'])sg.push({name:'Fastly',category:'CDN',severity:'info',detail:'Fastly CDN',icon:'fas fa-bolt'});
if(h.includes('recaptcha')||h.includes('g-recaptcha'))sg.push({name:'reCAPTCHA',category:'Bot Protection',severity:'medium',detail:'reCAPTCHA present',icon:'fas fa-robot'});
if(h.includes('hcaptcha'))sg.push({name:'hCaptcha',category:'Bot Protection',severity:'medium',detail:'hCaptcha present',icon:'fas fa-robot'});
if(h.includes('cf-turnstile'))sg.push({name:'Cloudflare Turnstile',category:'Bot Protection',severity:'medium',detail:'Turnstile CAPTCHA',icon:'fas fa-shield-virus'});
if(h.includes('datadome'))sg.push({name:'DataDome',category:'Bot Detection',severity:'high',detail:'DataDome bot layer',icon:'fas fa-ban'});
if(h.includes('perimeterx')||h.includes('px-captcha'))sg.push({name:'PerimeterX',category:'Bot Detection',severity:'high',detail:'PerimeterX',icon:'fas fa-ban'});
if(h.includes('kasada'))sg.push({name:'Kasada',category:'Bot Detection',severity:'high',detail:'Kasada',icon:'fas fa-ban'});
if(h.includes('imperva')||h.includes('incapsula'))sg.push({name:'Imperva',category:'WAF/Bot',severity:'high',detail:'Imperva WAF',icon:'fas fa-shield-alt'});
if(hd['x-ratelimit-limit']||hd['retry-after'])sg.push({name:'Rate Limiting',category:'Throttling',severity:'medium',detail:`Limit: ${hd['x-ratelimit-limit']||'?'}`,icon:'fas fa-tachometer-alt'});
const bv=sg.filter(s=>['high','medium'].includes(s.severity)&&s.category.includes('Bot')).length;return{signals:sg,bypassScore:bv===0?'Easy':bv<=1?'Moderate':bv<=2?'Hard':'Very Hard',hasWAF:sg.some(s=>s.category.includes('WAF')),hasCaptcha:sg.some(s=>s.category.includes('Bot Protection')),hasCDN:sg.some(s=>s.category.includes('CDN'))}}
function dAI($,html){const sg=[],h=html.toLowerCase(),tx=$.text();
if(h.includes('ai-generated')||h.includes('generated by ai'))sg.push({type:'declaration',msg:'AI-generated label found'});
if(h.includes('chatgpt')||h.includes('gpt-4')||h.includes('openai'))sg.push({type:'tool-mention',msg:'ChatGPT/GPT-4/OpenAI reference'});
if(h.includes('perplexity')||h.includes('gemini')||h.includes('copilot'))sg.push({type:'tool-mention',msg:'AI assistant reference'});
[/\b(as an ai|as a language model|my training data|my knowledge cutoff)\b/i,/\b(certainly!|absolutely!|great question|i'd be happy to)\b/i,/\b(in conclusion|it's worth noting|it's important to note)\b/i].forEach(p=>{if(p.test(tx))sg.push({type:'linguistic',msg:`AI pattern: "${p.source.slice(0,60)}"`})});
const avgSL=tx.split(/[.!?]+/).filter(s=>s.trim().length>10).reduce((a,s,_,ar)=>a+s.trim().split(' ').length/ar.length,0);if(avgSL>25)sg.push({type:'linguistic',msg:`High avg sentence length (${avgSL.toFixed(1)} words)`});
const ls=Math.min(100,sg.length*20);return{signals:sg,likelihoodScore:ls,likelyAI:ls>=40}}
function eSEO($,url){const is=[],ws=[],ps=[];const ti=$('title').text().trim(),de=$('meta[name="description"]').attr('content')||'',h1=$('h1').length,in2=$('img:not([alt])').length,ca=$('link[rel="canonical"]').attr('href')||'',ro=$('meta[name="robots"]').attr('content')||'',oi=$('meta[property="og:image"]').attr('content')||'';
if(!ti)is.push({msg:'Missing title'});else if(ti.length<30)ws.push({msg:`Title short (${ti.length})`});else if(ti.length>60)ws.push({msg:`Title long (${ti.length})`});else ps.push({msg:`Title OK (${ti.length})`});
if(!de)is.push({msg:'Missing meta description'});else if(de.length<120)ws.push({msg:`Desc short (${de.length})`});else if(de.length>160)ws.push({msg:`Desc long (${de.length})`});else ps.push({msg:`Desc OK (${de.length})`});
if(h1===0)is.push({msg:'No H1'});else if(h1>1)ws.push({msg:`Multiple H1 (${h1})`});else ps.push({msg:'Single H1'});
if(in2>0)ws.push({msg:`${in2} imgs missing alt`});else ps.push({msg:'All imgs have alt'});
if(!ca)ws.push({msg:'No canonical'});else ps.push({msg:'Canonical present'});
if(!oi)ws.push({msg:'No OG image'});else ps.push({msg:'OG image present'});
if(ro.includes('noindex'))is.push({msg:'noindex directive!'});
const sc=Math.round((ps.length/(ps.length+ws.length+is.length*2))*100);return{score:sc,issues:is,warnings:ws,passed:ps,title:ti,description:de,h1Count:h1,canonical:ca,robots:ro,ogImage:oi}}
function eSec($,html,headers={}){const f=[];const h=html.toLowerCase();if(!headers['strict-transport-security'])f.push({severity:'medium',type:'HTTPS',msg:'No HSTS header'});else f.push({severity:'pass',type:'HTTPS',msg:'HSTS present'});
if(!headers['content-security-policy'])f.push({severity:'medium',type:'CSP',msg:'No CSP header'});
if(!headers['x-frame-options'])f.push({severity:'low',type:'Clickjacking',msg:'No X-Frame-Options'});
if(!headers['x-content-type-options'])f.push({severity:'low',type:'MIME',msg:'No X-Content-Type-Options'});
if(h.includes('document.write('))f.push({severity:'low',type:'JS',msg:'document.write() found'});
if(h.match(/innerHTML\s*=/))f.push({severity:'low',type:'JS',msg:'innerHTML assignment found'});
const mx=html.match(/src="http:\/\//g)||[];if(mx.length)f.push({severity:'medium',type:'Mixed',msg:`${mx.length} mixed HTTP resources`});
const hf=$('form[action^="http://"]').length;if(hf>0)f.push({severity:'high',type:'Form',msg:`${hf} form(s) submit to HTTP`});
const pc=f.filter(fi=>fi.severity==='pass').length;return{score:Math.round((pc/Math.max(f.length,1))*100),findings:f}}
function eA11y($){const is=[],ws=[],ps=[];const ia=$('img:not([alt])').length;if(ia>0)is.push({msg:`${ia} imgs missing alt`});else ps.push({msg:'All imgs have alt'});
const il=$('input:not([aria-label]):not([aria-labelledby])').filter((i,el)=>{const id=$(el).attr('id');return!id||!$(`label[for="${id}"]`).length}).length;if(il>0)ws.push({msg:`${il} inputs missing label`});
if(!$('html[lang]').length)is.push({msg:'Missing lang on html'});else ps.push({msg:'HTML lang present'});
if(!$('main,[role="main"]').length)ws.push({msg:'No main landmark'});else ps.push({msg:'Main landmark present'});
if(!$('nav,[role="navigation"]').length)ws.push({msg:'No nav landmark'});
if($('a[href="#"]').length)ws.push({msg:`${$('a[href="#"]').length} empty anchors`});
return{score:Math.round((ps.length/(ps.length+ws.length+is.length*2))*100),issues:is,warnings:ws,passed:ps}}
function dAT($,html){const rm=[],tr=[];AS.forEach(sel=>{try{$(sel).each((i,el)=>{rm.push({type:'ad',selector:sel,snippet:$.html(el).substring(0,200)})});$(sel).remove()}catch(e){}});
$('script[src]').each((i,el)=>{const src=$(el).attr('src')||'';TP.forEach(p=>{if(p.test(src)){tr.push({type:'tracker',url:src});$(el).remove()}})});
$('script:not([src])').each((i,el)=>{const ct=$(el).html()||'';if(ct.includes('googletag')||ct.includes('adsbygoogle')||ct.includes('_gaq')||ct.includes('gtag(')){rm.push({type:'inline-ad',snippet:ct.substring(0,200)});$(el).remove()}});
$('iframe[src*="doubleclick"],iframe[src*="googlesyndication"]').each((i,el)=>{rm.push({type:'ad-iframe',url:$(el).attr('src')});$(el).remove()});
return{removed:rm,trackers:tr,totalCleaned:rm.length+tr.length}}
function eMeta(html,$,baseUrl){const m={title:$('title').first().text()||'',description:$('meta[name="description"]').attr('content')||$('meta[property="og:description"]').attr('content')||'',keywords:$('meta[name="keywords"]').attr('content')||'',author:$('meta[name="author"]').attr('content')||'',ogImage:$('meta[property="og:image"]').attr('content')||'',ogTitle:$('meta[property="og:title"]').attr('content')||'',ogUrl:$('meta[property="og:url"]').attr('content')||'',ogSiteName:$('meta[property="og:site_name"]').attr('content')||'',ogType:$('meta[property="og:type"]').attr('content')||'',twitterCard:$('meta[name="twitter:card"]').attr('content')||'',twitterSite:$('meta[name="twitter:site"]').attr('content')||'',twitterTitle:$('meta[name="twitter:title"]').attr('content')||'',twitterImage:$('meta[name="twitter:image"]').attr('content')||'',favicon:$('link[rel*="icon"]').first().attr('href')||'/favicon.ico',language:$('html').attr('lang')||'en',charset:$('meta[charset]').attr('charset')||'utf-8',viewport:$('meta[name="viewport"]').attr('content')||'',robots:$('meta[name="robots"]').attr('content')||'',canonical:$('link[rel="canonical"]').attr('href')||'',generator:$('meta[name="generator"]').attr('content')||'',theme:$('meta[name="theme-color"]').attr('content')||''};Object.keys(m).forEach(k=>{if(m[k]&&!iA(m[k])&&(k.includes('Image')||k.includes('icon')||k.includes('canonical')))m[k]=mA(m[k],baseUrl)});return m}
function eImg($,baseUrl){const imgs=new Set,res=[];$('img[src]').each((i,el)=>{const src=$(el).attr('src'),alt=$(el).attr('alt'),ti=$(el).attr('title');if(src){const ab=mA(src,baseUrl);if(!imgs.has(ab)){imgs.add(ab);res.push({type:'image',subtype:'content',url:ab,alt:alt||'Image',title:ti||'',icon:'fas fa-image'})}}});
$('picture source[srcset],img[srcset]').each((i,el)=>{const ss=$(el).attr('srcset');if(ss){ss.split(',').forEach(s=>{const u=s.trim().split(' ')[0];if(u){const ab=mA(u,baseUrl);if(!imgs.has(ab)){imgs.add(ab);res.push({type:'image',subtype:'responsive',url:ab,alt:'Responsive',icon:'fas fa-image'})}}})}});
['og:image','twitter:image'].forEach(n=>{const ct=$(`meta[property="${n}"],meta[name="${n}"]`).attr('content');if(ct){const ab=mA(ct,baseUrl);if(!imgs.has(ab)){imgs.add(ab);res.push({type:'image',subtype:'social',url:ab,alt:n,icon:'fas fa-image'})}}});
$('link[rel*="icon"]').each((i,el)=>{const hr=$(el).attr('href');if(hr){const ab=mA(hr,baseUrl);if(!imgs.has(ab)){imgs.add(ab);res.push({type:'image',subtype:'icon',url:ab,alt:'Icon',icon:'fas fa-star'})}}});return res}
function eMI($,baseUrl){const me=[],if2=[];$('video').each((i,el)=>{const src=$(el).attr('src')||$('source',el).first().attr('src');const po=$(el).attr('poster');if(src)me.push({type:'video',url:mA(src,baseUrl),poster:po?mA(po,baseUrl):'',width:$(el).attr('width')||'',height:$(el).attr('height')||''})});
$('audio').each((i,el)=>{const src=$(el).attr('src')||$('source',el).first().attr('src');if(src)me.push({type:'audio',url:mA(src,baseUrl)})});
$('source[src]').each((i,el)=>{const src=$(el).attr('src'),ty=$(el).attr('type')||'';if(src&&(ty.includes('video')||ty.includes('audio')))me.push({type:ty.includes('video')?'video':'audio',url:mA(src,baseUrl),mimeType:ty})});
$('iframe[src]').each((i,el)=>{const src=$(el).attr('src');if(src&&!TP.some(p=>p.test(src))){const ab=mA(src,baseUrl);if2.push({url:ab,title:$(el).attr('title')||'',width:$(el).attr('width')||'',height:$(el).attr('height')||'',isYoutube:/youtube\.com|youtu\.be/.test(ab),isVimeo:/vimeo\.com/.test(ab),isMap:/maps\.google|maps\.apple|openstreetmap/.test(ab),isSocial:/twitter\.com|facebook\.com|instagram\.com/.test(ab)})}});return{media:me,iframes:if2}}
function aP(html,$,baseUrl){const lk=new Set,sc=new Set,st=new Set,il=new Set,el2=new Set,allRes=[],iR=eImg($,baseUrl);allRes.push(...iR);
$('a[href]').each((i,el)=>{const hr=$(el).attr('href'),tx=$(el).text().trim(),ti=$(el).attr('title');if(hr&&!hr.startsWith('#')&&!hr.startsWith('javascript:')){const ab=mA(hr,baseUrl);lk.add(ab);allRes.push({type:'link',url:ab,text:tx||ti||'Link',icon:'fas fa-link'});try{new U(ab).hostname===new U(baseUrl).hostname?il.add(ab):el2.add(ab)}catch{}}});
$('script[src]').each((i,el)=>{const src=$(el).attr('src');if(src){const ab=mA(src,baseUrl);sc.add(ab);allRes.push({type:'script',url:ab,icon:gI(ab)})}});
$('link[rel="stylesheet"],link[href$=".css"]').each((i,el)=>{const hr=$(el).attr('href');if(hr){const ab=mA(hr,baseUrl);st.add(ab);allRes.push({type:'stylesheet',url:ab,icon:'fab fa-css3-alt'})}});
$('iframe[src],embed[src],object[data]').each((i,el)=>{const src=$(el).attr('src')||$(el).attr('data');if(src){const ab=mA(src,baseUrl);allRes.push({type:'embed',url:ab,title:$(el).attr('title')||'Embed',icon:'fas fa-window-restore'})}});
$('video[src],audio[src],source[src]').each((i,el)=>{const src=$(el).attr('src'),ty=$(el).attr('type');if(src){const ab=mA(src,baseUrl);allRes.push({type:'media',url:ab,mediaType:ty||'unknown',icon:'fas fa-video'})}});
const{media,iframes}=eMI($,baseUrl);
return{totalLinks:lk.size,internalLinks:il.size,externalLinks:el2.size,images:iR.length,scripts:sc.size,stylesheets:st.size,hasForm:$('form').length>0,hasVideo:$('video').length>0,hasAudio:$('audio').length>0,textLength:$.text().length,wordCount:$.text().split(/\s+/).filter(w=>w.length>0).length,readingTime:Math.ceil($.text().split(/\s+/).filter(w=>w.length>0).length/200),headings:{h1:$('h1').length,h2:$('h2').length,h3:$('h3').length,h4:$('h4').length,h5:$('h5').length,h6:$('h6').length},resources:allRes,media,iframes,socialMedia:{facebook:$('a[href*="facebook.com"]').length,twitter:$('a[href*="twitter.com"],a[href*="x.com"]').length,instagram:$('a[href*="instagram.com"]').length,linkedin:$('a[href*="linkedin.com"]').length,youtube:$('a[href*="youtube.com"]').length,tiktok:$('a[href*="tiktok.com"]').length,pinterest:$('a[href*="pinterest.com"]').length},forms:{total:$('form').length,inputs:$('input').length,textareas:$('textarea').length,selects:$('select').length,buttons:$('button,input[type="submit"],input[type="button"]').length},performance:{totalElements:$('*').length,inlineScripts:$('script:not([src])').length,externalScripts:$('script[src]').length,inlineStyles:$('style').length,externalStyles:$('link[rel="stylesheet"]').length}}}
function pH(html,baseUrl,proxyBase){const $=c.load(html);const uA={href:['a','link'],src:['img','script','iframe','source','embed','video','audio'],action:['form'],'data-src':['*'],srcset:['img','source'],poster:['video']};Object.entries(uA).forEach(([at,sls])=>{sls.forEach(sel=>{const els=sel==='*'?$(`[${at}]`):$(`${sel}[${at}]`);els.each((i,element)=>{const $el=$(element);let val=$el.attr(at);if(!val)return;if(at==='srcset'){const sv=val.split(',').map(s=>{const p=s.trim().split(' ');p[0]=mA(p[0],baseUrl);return p.join(' ')});$el.attr(at,sv.join(', '))}else if(at==='href'&&sel==='a'){if(!val.startsWith('#')&&!val.startsWith('javascript:')&&!val.startsWith('mailto:')){const ab=mA(val,baseUrl);$el.attr(at,`${proxyBase}/api/proxy?url=${encodeURIComponent(ab)}`)}}else if(iS(val)||at!=='href')$el.attr(at,mA(val,baseUrl))})})});
SH.forEach(n=>{$(`meta[http-equiv="${n}"]`).remove();$(`meta[name="${n}"]`).remove()});$('meta[http-equiv="X-Frame-Options"]').remove();$('head').prepend('<meta http-equiv="Content-Security-Policy" content="frame-ancestors *;">');
$('style').each((i,el)=>{const $s=$(el);let ct=$s.html();if(ct){ct=ct.replace(/url\(['"]?([^'"()]+)['"]?\)/g,(m,u)=>`url('${mA(u.trim(),baseUrl)}')`);$s.html(ct)}});
$('[style]').each((i,el)=>{const $el=$(el);let s=$el.attr('style');if(s){s=s.replace(/url\(['"]?([^'"()]+)['"]?\)/g,(m,u)=>`url('${mA(u.trim(),baseUrl)}')`);$el.attr('style',s)}});return $.html()}

function optimizeHtml(html,baseUrl,proxyBase,opts={}){
  const $=c.load(html);
  const log=[];
  if(opts.removeAds){AS.forEach(sel=>{try{const n=$(sel).length;if(n>0){log.push({type:'ads',msg:`Removed ${n} ad element(s): ${sel}`});$(sel).remove()}}catch(e){}});$('script:not([src])').each((i,el)=>{const ct=$(el).html()||'';if(ct.includes('googletag')||ct.includes('adsbygoogle')||ct.includes('_gaq')){log.push({type:'ads',msg:'Removed inline ad script'});$(el).remove()}});$('iframe[src*="doubleclick"],iframe[src*="googlesyndication"]').each((i,el)=>{log.push({type:'ads',msg:`Removed ad iframe: ${$(el).attr('src')}`});$(el).remove()});}
  if(opts.removeTrackers){$('script[src]').each((i,el)=>{const src=$(el).attr('src')||'';if(TP.some(p=>p.test(src))){log.push({type:'trackers',msg:`Blocked tracker: ${src}`});$(el).remove()}});$('noscript').each((i,el)=>{const ct=$(el).html()||'';if(ct.includes('facebook.com/tr')||ct.includes('google-analytics')){log.push({type:'trackers',msg:'Removed tracker noscript'});$(el).remove()}});}
  if(opts.removeMetaTags){$('meta[name="generator"]').remove();$('meta[name="author"]').remove();log.push({type:'meta',msg:'Removed generator/author meta tags'});}
  if(opts.removeComments){const cheer=$;$('*').contents().each(function(){if(this.type==='comment'){log.push({type:'comments',msg:`Removed HTML comment: ${this.data.trim().slice(0,40)}`});$(this).remove()}});}
  if(opts.removeInlineStyles){$('[style]').each((i,el)=>{log.push({type:'styles',msg:`Removed inline style from <${el.tagName}>`});$(el).removeAttr('style')});log.push({type:'styles',msg:'Removed all inline style attributes'});}
  if(opts.removeScripts){$('script').remove();log.push({type:'scripts',msg:'Removed all script tags'});}
  if(opts.removeIframes){$('iframe').remove();log.push({type:'iframes',msg:'Removed all iframes'});}
  if(opts.addEruda){$('body').append(`<script src="https://cdn.jsdelivr.net/npm/eruda"></script><script>eruda.init();</script>`);log.push({type:'inject',msg:'Injected Eruda mobile devtools'});}
  if(opts.addAntiRedirect){$('head').append(`<script>(function(){var _open=window.open;window.open=function(){return null};var _assign=window.location.__lookupSetter__&&window.location.__lookupSetter__('href');Object.defineProperty(window,'location',{get:function(){return window.location},set:function(v){console.warn('[AntiRedirect] Blocked redirect to:',v)},configurable:true});document.addEventListener('click',function(e){var a=e.target.closest('a');if(a&&a.target==='_blank'){e.preventDefault();console.warn('[AntiRedirect] Blocked _blank link:',a.href)}},{capture:true});}());</script>`);log.push({type:'inject',msg:'Injected anti-redirect code'});}
  if(opts.addFloatingInspector){const panel=`<div id="_pf_insp" style="position:fixed;bottom:70px;right:16px;z-index:2147483647;background:#0a0a0f;border:1px solid #dc2626;border-radius:12px;padding:16px;width:320px;max-height:60vh;overflow-y:auto;font-family:monospace;font-size:11px;color:#e5e7eb;display:none;box-shadow:0 8px 32px rgba(220,38,38,0.3)"><div style="color:#ef4444;font-weight:bold;margin-bottom:8px;display:flex;justify-content:space-between"><span>🔍 Page Inspector</span><button onclick="document.getElementById('_pf_insp').style.display='none'" style="background:none;border:none;color:#9ca3af;cursor:pointer;font-size:14px">✕</button></div><div id="_pf_insp_content">Loading...</div></div><button id="_pf_btn" onclick="document.getElementById('_pf_insp').style.display=document.getElementById('_pf_insp').style.display==='none'?'block':'none';document.getElementById('_pf_insp_content').innerHTML='<b style=color:#facc15>Title:</b> '+document.title+'<br><b style=color:#facc15>URL:</b> '+location.href+'<br><b style=color:#facc15>Scripts:</b> '+document.scripts.length+'<br><b style=color:#facc15>Images:</b> '+document.images.length+'<br><b style=color:#facc15>Links:</b> '+document.links.length+'<br><b style=color:#facc15>Forms:</b> '+document.forms.length+'<br><b style=color:#facc15>Cookies:</b> '+(document.cookie?document.cookie.split(';').length:0)+'<br><b style=color:#facc15>LocalStorage:</b> '+localStorage.length+'<br><b style=color:#facc15>Referrer:</b> '+(document.referrer||'none')+'<br><b style=color:#facc15>Charset:</b> '+document.characterSet+'<br><b style=color:#facc15>Lang:</b> '+document.documentElement.lang+'<br><b style=color:#facc15>Viewport:</b> '+window.innerWidth+'×'+window.innerHeight" style="position:fixed;bottom:16px;right:16px;z-index:2147483647;background:#dc2626;color:#fff;border:none;border-radius:50%;width:48px;height:48px;cursor:pointer;font-size:18px;box-shadow:0 4px 16px rgba(220,38,38,0.5);display:flex;align-items:center;justify-content:center" title="ProxyForge Inspector">🔍</button>`;$('body').append(panel);log.push({type:'inject',msg:'Injected floating page inspector'});}
  if(opts.rewriteLinks){$('a[href]').each((i,el)=>{const hr=$(el).attr('href');if(hr&&!hr.startsWith('#')&&!hr.startsWith('javascript:')&&!hr.startsWith('mailto:')){const ab=mA(hr,baseUrl);$(el).attr('href',`${proxyBase}/api/proxy?url=${encodeURIComponent(ab)}`)}});}
  SH.forEach(n=>{$(`meta[http-equiv="${n}"]`).remove();$(`meta[name="${n}"]`).remove()});$('meta[http-equiv="X-Frame-Options"]').remove();$('head').prepend('<meta http-equiv="Content-Security-Policy" content="frame-ancestors *;">');
  if(opts.addViewportMeta&&!$('meta[name="viewport"]').length){$('head').append('<meta name="viewport" content="width=device-width,initial-scale=1">');log.push({type:'inject',msg:'Added viewport meta'});}
  return{html:$.html(),log}}

async function fP(url,req){try{const uo=new U(url);const pb=req?`${req.protocol}://${req.get('host')}`:'';const hd={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36','Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8','Accept-Language':'en-US,en;q=0.9','Connection':'keep-alive','Upgrade-Insecure-Requests':'1'};const st=Date.now();const res=await axios.get(url,{headers:hd,timeout:30000,maxRedirects:5,validateStatus:s=>s<500});const rt=Date.now()-st;const ct=res.headers['content-type']||'';if(!ct.includes('text/html'))throw new Error('Not HTML');
const rH=res.data;const $r=c.load(rH);const ar=dAT($r,rH);const md=eMeta(rH,$r,url);const an=aP(rH,$r,url);const te=dT($r,rH);const se=eSEO($r,url);const sc=eSec($r,rH,res.headers);const ac=eA11y($r);const bp=dBP($r,rH,res.headers);const ai=dAI($r,rH);const vd=await gVD(url,$r,rH);const ph=pH(rH,url,pb);const rs=Buffer.byteLength(rH,'utf8');const ps=Buffer.byteLength(ph,'utf8');
return{success:true,url,originalUrl:url,status:res.status,statusText:res.statusText||'OK',contentType:ct,responseTime:rt,responseHeaders:Object.fromEntries(Object.entries(res.headers).slice(0,20)),size:{original:rs,processed:ps,compression:((rs-ps)/rs*100).toFixed(2)+'%'},metadata:md,analysis:an,visualData:vd,technologies:te,seo:se,security:sc,accessibility:ac,botProtection:bp,aiContent:ai,adsRemoved:ar,contents:ph,processedLinks:true,securityRemoved:true,timestamp:new Date().toISOString(),requestId:x.randomBytes(8).toString('hex')}}catch(err){throw{success:false,error:err.message,url,status:err.response?.status||0,statusText:err.response?.statusText||'Error',timestamp:new Date().toISOString(),requestId:x.randomBytes(8).toString('hex')}}}

app.get('/api/proxy',async(req,res)=>{try{const{url}=req.query;if(!url)return res.status(400).send('<html><body><h1>400</h1><p>URL required</p></body></html>');const result=await fP(url,req);res.setHeader('Content-Type','text/html');res.send(result.contents)}catch(err){res.status(err.status||500).send(`<html><body><h1>${err.status||500}</h1><p>${err.error||'Error'}</p></body></html>`)}});
app.get('/api/html/proxy',async(req,res)=>{try{const{url}=req.query;if(!url)return res.status(400).json({success:false,error:'URL required'});const result=await fP(url,req);res.json({html:result.contents})}catch(err){res.status(err.status||500).json({error:err.error||'Error'})}});
app.get('/api/json/proxy',async(req,res)=>{try{const{url}=req.query;if(!url)return res.status(400).json({success:false,error:'URL required'});const result=await fP(url,req);res.json(result)}catch(err){res.status(err.status||500).json(err)}});
app.post('/api/proxy',async(req,res)=>{try{const{url}=req.body;if(!url)return res.status(400).send('<html><body><h1>400</h1></body></html>');const result=await fP(url,req);res.setHeader('Content-Type','text/html');res.send(result.contents)}catch(err){res.status(err.status||500).send(`<html><body><h1>${err.status||500}</h1></body></html>`)}});
app.post('/api/html/proxy',async(req,res)=>{try{const{url}=req.body;if(!url)return res.status(400).json({success:false,error:'URL required'});const result=await fP(url,req);res.json({html:result.contents})}catch(err){res.status(err.status||500).json({error:err.error||'Error'})}});
app.post('/api/json/proxy',async(req,res)=>{try{const{url}=req.body;if(!url)return res.status(400).json({success:false,error:'URL required'});const result=await fP(url,req);res.json(result)}catch(err){res.status(err.status||500).json(err)}});

app.get('/api/optimize',async(req,res)=>{try{const{url,...opts}=req.query;if(!url)return res.status(400).json({success:false,error:'URL required'});const pb=`${req.protocol}://${req.get('host')}`;const hd={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36','Accept':'text/html,*/*;q=0.8','Accept-Language':'en-US,en;q=0.9'};const rsp=await axios.get(url,{headers:hd,timeout:30000,maxRedirects:5,validateStatus:s=>s<500});const ct=rsp.headers['content-type']||'';if(!ct.includes('text/html'))return res.status(400).json({success:false,error:'Not HTML'});const bO={removeAds:opts.removeAds==='1'||opts.removeAds==='true',removeTrackers:opts.removeTrackers==='1'||opts.removeTrackers==='true',removeMetaTags:opts.removeMetaTags==='1'||opts.removeMetaTags==='true',removeComments:opts.removeComments==='1'||opts.removeComments==='true',removeInlineStyles:opts.removeInlineStyles==='1'||opts.removeInlineStyles==='true',removeScripts:opts.removeScripts==='1'||opts.removeScripts==='true',removeIframes:opts.removeIframes==='1'||opts.removeIframes==='true',addEruda:opts.addEruda==='1'||opts.addEruda==='true',addAntiRedirect:opts.addAntiRedirect==='1'||opts.addAntiRedirect==='true',addFloatingInspector:opts.addFloatingInspector==='1'||opts.addFloatingInspector==='true',rewriteLinks:opts.rewriteLinks==='1'||opts.rewriteLinks==='true',addViewportMeta:opts.addViewportMeta==='1'||opts.addViewportMeta==='true'};const{html:oh,log}=optimizeHtml(rsp.data,url,pb,bO);const orig=Buffer.byteLength(rsp.data,'utf8');const proc=Buffer.byteLength(oh,'utf8');res.json({success:true,url,originalSize:orig,optimizedSize:proc,saved:orig-proc,savedPercent:((orig-proc)/orig*100).toFixed(2)+'%',appliedOptions:bO,log,html:oh,timestamp:new Date().toISOString()})}catch(err){res.status(500).json({success:false,error:err.message})}});

app.post('/api/optimize',async(req,res)=>{try{const{url,options={}}=req.body;if(!url)return res.status(400).json({success:false,error:'URL required'});const pb=`${req.protocol}://${req.get('host')}`;const hd={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36','Accept':'text/html,*/*;q=0.8'};const rsp=await axios.get(url,{headers:hd,timeout:30000,maxRedirects:5,validateStatus:s=>s<500});const ct=rsp.headers['content-type']||'';if(!ct.includes('text/html'))return res.status(400).json({success:false,error:'Not HTML'});const{html:oh,log}=optimizeHtml(rsp.data,url,pb,options);const orig=Buffer.byteLength(rsp.data,'utf8');const proc=Buffer.byteLength(oh,'utf8');res.json({success:true,url,originalSize:orig,optimizedSize:proc,saved:orig-proc,savedPercent:((orig-proc)/orig*100).toFixed(2)+'%',appliedOptions:options,log,html:oh,timestamp:new Date().toISOString()})}catch(err){res.status(500).json({success:false,error:err.message})}});

app.get('/api/inject-inspector',async(req,res)=>{try{const{url}=req.query;if(!url)return res.status(400).send('<html><body>URL required</body></html>');const pb=`${req.protocol}://${req.get('host')}`;const hd={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36','Accept':'text/html,*/*;q=0.8'};const rsp=await axios.get(url,{headers:hd,timeout:30000,maxRedirects:5,validateStatus:s=>s<500});const ct=rsp.headers['content-type']||'';if(!ct.includes('text/html'))return res.status(400).send('<html><body>Not HTML</body></html>');const{html:oh}=optimizeHtml(rsp.data,url,pb,{rewriteLinks:true,addFloatingInspector:true,addAntiRedirect:true});res.setHeader('Content-Type','text/html');res.send(oh)}catch(err){res.status(500).send(`<html><body>Error: ${err.message}</body></html>`)}});

app.get('/api/health',(req,res)=>{res.json({status:'OK',timestamp:new Date().toISOString(),service:'ProxyForge API',version:'4.2.0',uptime:process.uptime(),memory:process.memoryUsage()})});
app.get('/api/docs',(req,res)=>{res.json({name:'ProxyForge API',version:'4.2.0',endpoints:{'GET /api/proxy':'Proxied HTML','GET /api/html/proxy':'HTML in JSON','GET /api/json/proxy':'Full JSON analysis','GET /api/optimize':'Optimized HTML with options','POST /api/optimize':'Optimized HTML (POST body)','GET /api/inject-inspector':'Page with floating inspector injected','GET /api/health':'Health check'}})});
app.use((error,req,res,next)=>{res.status(500).json({success:false,error:'Internal error',timestamp:new Date().toISOString()})});
app.use((req,res)=>{res.status(404).json({success:false,error:'Not found',timestamp:new Date().toISOString()})});
app.listen(P,'0.0.0.0',()=>{console.log(`\u{1F525} ProxyForge API v4.2.0 on port ${P}`)});module.exports=app;